import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Hospital {
	public static void main(String[] args) {
		System.out.println("Hospital JDBC");

		String url = "jdbc:postgresql://127.0.0.1:5432/hospital";
		String user = "postgres";
		String pass = "1q2w3e";
		Hospital hospital = new Hospital();
		try {
			Class.forName("org.postgresql.Driver");
			int err = hospital.createTableMedic(url, user, pass);
			if (err == 0) {
				System.out.println("table medic created successfully");
			} else {
				System.out.println("error creating table medic");
			}

		} catch (Exception e) {
				System.out.println("error loading driver: " + e.getMessage());
		}}

	private int createTableMedic(String url, String user, String pass)
			throws SQLException {
		int err = 0;
		Connection conn = DriverManager.getConnection(url, user, pass);
		String query = "CREATE TABLE medic (id bigint GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(100), specialization VARCHAR(50), emp_date date NULL);";
		System.out.println("create table medic: " + query);
		Statement stmt = conn.createStatement();
		err = stmt.executeUpdate(query);
		conn.close();
		return err;
	}
}
